vuejs/devtools-v6

- src/backend/index.js
in case that vue instance can't be detected when using 'html' as root el. my previous issue: #66
> scan document.documentElement itself

- src/devtools/components/Instance.vue
- src/devtools/components/Tree.vue
navigation use arrow keys, navigate logic is like Chrome devtools 'Element' tab.
only trick is that I get all visible instances from DOM, but it works well.
> add arrow key navigation

- test/specs/test.js
> added test spec for state export/import

- src/devtools/components/VuexStateInspector.vue
- test/specs/test.js
ref #102 
Just some eye-candy regarding Vuex state import/export. I added watcher, because autofocus seemed to work only first time.
> styles for vuex state import/export

- src/backend/index.js
> Fix too restrictive RegExp

- src/devtools/components/VuexHistory.vue
I guess this feature has been requested several times already  (#134, #112 ), so went ahead and implemented it. It allows to use both simple string search and RegExes. Appropriate error is displayed if RegEx can't be compiled.
Unfortunately I couldn't get tests to start, so I did not write any. I'll try to do that but any help would be appreciated.
> adds mutation filtering to Vuex tab

- src/devtools/components/VuexHistory.vue
- test/specs/test.js
I managed to get Selenium working (I have to wait 60 secs before first assertion fires though...). I added tests, and found a little bug concerning display of 'invalid regex' label. 
I you want me to add anything more, just let me know.
> add tests for vuex filter, fix invalid regex display

- src/devtools/global.styl
> Never use local MaterialIcons fonts

- shells/chrome/src/detector.js
Fixed an error when declaring property "constructor" in data.
> property "constructor" in data with error fixed.

- package.json
- src/devtools/components/DataField.vue
- src/devtools/views/components/ComponentInspector.vue
- src/util.js
Fixes #258. Needs: npm install (added lodash.groupBy as dependency)
> Break props, data and computed in different sections and make them searchable 

- src/devtools/views/components/ComponentInspector.vue
> corrected import for case-sensitive file systems

- src/backend/index.js
> Fix props display when defined only in mixin

- src/devtools/App.vue
- src/devtools/components/ActionHeader.vue
- src/devtools/views/components/ComponentInspector.vue
- src/devtools/views/vuex/VuexStateInspector.vue
Keep header static.
Before: 
After:
> Component inspector header static

- src/devtools/components/DataField.vue
> Animated arrow

- shells/chrome/src/detector.js
- shells/chrome/src/devtools.js
- shells/chrome/src/hook.js
* Don't leak variable "script"
* Fix XML view in FF. This fixes #356 and is similar to #357 but uses an "instanceof"
> Fix inject problems

- README.md
This helps a lot newcomers (like me) to solve the problem using the main repository page.
> Adding session to help newcomers with commom problems and how to solve them.

- src/devtools/views/events/EventInspector.vue
Unused component removed from event inspection
> Unused component removed

- src/devtools/components/ActionHeader.vue
- src/devtools/views/components/ComponentInspector.vue
This is updated version of this PR: #285 
Original PR introduced minor issue with no space between title and search component.
Fork from which initial PR was created is listed as `unknown repository`, so I decided to create fresh one.
> Hide inspect button outside chrome devtools context

- src/backend/index.js
- src/backend/vuex.js
- vue1-test.html
- Fix Data editing for Vue@1.x (tested with 1.0.28)
- Fix Vuex@1.x not having getters
> Improve Vue@1.x compat

- src/devtools/env.js
- src/devtools/index.js
> 552 - Move code to initBodyClass

- shells/dev/target/NativeTypes.vue
- src/devtools/components/DataField.vue
- src/util.js
- Function names
- Native objects display values
> Escape HTML for more data

- src/backend/index.js
> fix: duplicate root instances

- src/devtools/views/components/ComponentTree.vue
> fix tree navigation with arrow keys

- src/backend/events.js
- src/devtools/index.js
> clean events on refresh

- package.json
- shells/createConfig.js
- shells/dev/target/EventChild.vue
- src/backend/index.js
- src/backend/perf.js
- src/backend/vuex.js
- src/devtools/App.vue
- src/devtools/components/ActionHeader.vue
- src/devtools/filters.js
- src/devtools/index.js
- src/devtools/locales/en.js
- src/devtools/router.js
- src/devtools/store/index.js
- src/devtools/style/global.styl
- src/devtools/style/variables.styl
- src/devtools/views/events/EventsHistory.vue
- src/devtools/views/perf/ComponentRenderDetails.vue
- src/devtools/views/perf/ComponentRenderStats.vue
- src/devtools/views/perf/FramerateGraph.vue
- src/devtools/views/perf/FramerateMarkerInspector.vue
- src/devtools/views/perf/FramesPerSecondGraph.vue
- src/devtools/views/perf/PerfTab.vue
- src/devtools/views/perf/module.js
- src/devtools/views/vuex/VuexTab.vue
- src/shared-data.js
- yarn.lock
> feat: performance tab

- src/devtools/App.vue
Fixes vuejs#815
Not the most complex commit ever 😉
> Add missing return statement to ctrl+Digit4 key event

- src/backend/index.js
> fix: Fix component refs, closes #774

- cypress/integration/components-tab.js
- shells/dev/target/Other.vue
- shells/dev/target/Target.vue
- src/backend/index.js
- src/devtools/components/StateInspector.vue
> feat: Add $attrs to StateInspector, closes #734

- README.md
Added a short description of how to quick start in oneself project,most people  in issue want to find
> :memo: setting

- src/util.js
https://github.com/vuejs/vue-devtools/issues/994
> fix: Cannot read property of undefined issue

- packages/app-backend/src/clone.js
Fixes #1099
Fixes errors like this (when using the new Vuex backend):
> fix: Make sure the 'then' property exists on the object before checking if its a function #1099

- README.md
addressing issue #767 :
- adding more details in the installation instructions
- fixing the mentioned path which was wrong
- mentioning how to use `npm` instead of `yarn`
> updating installation instruction

- packages/app-frontend-legacy/src/components/DataField.vue
- packages/app-frontend-legacy/src/locales/en.js
- packages/app-frontend/src/features/inspector/DataField.vue
- packages/app-frontend/src/locales/en.js
Implements copyPath method.
----
Copied!  `"reactiveObject.hello.world"`
> feat: implements copyPath method

- docs/plugin/plugins-guide.md
grammar correction in sentence
> docs: Plugins Guide grammar

- docs/guide/faq.md
> docs: Update faq.md

- packages/app-backend-vue2/src/components/tree.ts
Referred in #1518
In **Vue 2.x** projects, backendApi `api.visitComponentTree` is not called in component tree 's  `capture` method
If it was not intended to drop this function call by design, then it was a mistake since it never triggers `hook.on.visitComponentTree` when traversing through the component tree,  leading the userland plugin failed to perform component parsing.
It's deeply needed in our team because we are developing a custom plugin strongly relied to it.
Please consider if it's possible to fix this feature in the `app-backend-vue2` package, thanks a lot!
> fix: Call `api.visitComponentTree` in Vue2's backend api

- packages/app-backend-api/src/hooks.ts
Fix typo on "occured" to "occurred" 🙂
> fix: error typo on "occured" to "occurred"

- packages/app-backend-vue3/src/components/data.ts
> fix(dataField): 'effect.raw' has been unavailable

- packages/app-backend-vue3/src/components/data.ts
Fixes https://github.com/vuejs/devtools/issues/1567
> fix: remove redundant console.log

- packages/app-backend-vue3/src/components/tree.ts
> fix(vue3): remove duplicate children and inherit 'inactive' state, closes #1554

- packages/app-backend-vue2/src/components/tree.ts
> fix(vue2): mark functional component

- packages/app-backend-core/src/hook.ts
Fixes a simple typo in a warning log message.
> chore: fix typo.

- packages/app-backend-vue2/src/components/data.ts
Add support for 2.7 built-in Composition API setup state.
> feat: support inspecting 2.7 setup state

- packages/app-backend-core/src/index.ts
> fix: state not updating

- packages/app-backend-vue2/src/plugin.ts
This PR fixes the vue2 plugin logo url
Fix
Previous
---
> fixes broken vue2 logo in plugin 

- packages/app-frontend/src/views/routes/RoutesMeta.vue
> feat(vue2): Add meta field into routes panel

- .circleci/config.yml
> ci: upgrade nodejs version

- packages/shell-electron/index.js
optimized repeat judgment => 'typeof window !== 'undefined''
> refactor(shell-electron): optimized repeat judgment

- packages/shell-chrome/src/devtools-background.js
- packages/shell-firefox/src/devtools-background.js
> chore: change devtools panel name to legacy
