vuejs/devtools-v6

src/devtools/components/Tree.vue

I forgot to remove the keyup listener on destroy, so it may add multiple listeners to document when the target document refreshed.

arrow key navigation bug fix

---

src/devtools/components/ComponentInspector.vue
src/devtools/components/DataField.vue
test/specs/test.js

ref #107 
Now keys in inspector are displayed alphabetically, additionally I removed `limitBy` so it should work with Vue 2.0

sorting keys alphabetically

---

src/devtools/components/ComponentInspector.vue

The component properties within the component inspector are not always sorted in the correct alphabetical order. An example of this can be found in the TransitionGroup component in the "HackerNews Clone Example" from the docs:
This pr fixes the sorting of the properties.

Fix sorting of component properties in component inspector

---

shells/chrome/src/detector.js

`document.all` returns an `HTMLAllCollection` which has some, uhm, [special](http://stackoverflow.com/questions/10350142/why-is-document-all-falsy), behavior. This is causing errors when es6-shim is present, which in some cases overwrites the native `Array.prototype.find` with its own implementation.
This is an attempt to prevent vue-devtools from throwing an error in Chrome when es6-shim is present.
See: https://github.com/paulmillr/es6-shim/issues/428

Avoid using document.all

---

src/devtools/mixins/key-nav.js

Changed for mounted and destroyed respectively to fix not working arrow keys navigation.

Change attached and detached lifecycle hooks in key-nav mixin

---

src/backend/events.js
src/backend/index.js
src/devtools/components/EventsHistory.vue

Currently the re-emit events feature in the events history pane is broken. We can't re-emit events on conditionally rendered components anyways (the component for the event may be removed).

Remove currently broken re-emit events feature in events history pane

---

src/devtools/store/modules/vuex/index.js

Just added call to `reset` on `vuex/INIT` mutation. Fixes #174

flush Vuex history on reload

---

shells/dev/index.html
shells/dev/target/Other.vue
src/devtools/common.styl
src/devtools/components/Actions.vue
src/devtools/components/App.vue
src/devtools/components/ComponentInspector.vue
src/devtools/components/ComponentInstance.vue
src/devtools/components/ComponentTree.vue
src/devtools/components/ComponentsTab.vue
src/devtools/components/EventInspector.vue
src/devtools/components/EventsHistory.vue
src/devtools/components/EventsTab.vue
src/devtools/components/ScrollPane.vue
src/devtools/components/SplitPane.vue
src/devtools/components/VuexHistory.vue
src/devtools/components/VuexStateInspector.vue
src/devtools/components/VuexTab.vue
src/devtools/global.styl
test/specs/test.js

There's a bunch of updates here. I still want to clean up some code but it's getting there. I'll try to summarize a bit.
This component allows the top to stay put and the rest to scroll with overlay scrolling.
The search bar is now always to the left with buttons to the far right of it. They're all very squishy too.
We add more comfortable spacing and show icon text based on the width / height of the devtools. Looks "good" from 450px up.
The "active" color is set through one variable now, so basically everywhere you see blue can be easily switched to another color. I'd like to add a "switch" to enable a dark mode a little bit down the line as well.
Excited to hear what you all think.

consistency and responsive adjustments

---

src/backend/events.js

This pull request tries to fix #220. 
@yyx990803 : If events get broadcastet in Vue 1.x, the arguments on the Vue.$emit function are slightly different (first argument is object instead of string), right? With this pull request I try to compensate for that.

Fix broadcasting events with Vue 1.x (fixes #220)

---

src/backend/events.js

When using Vue 1.0.28, `pre-hook` events are showing in the Events Tab
See #229

Ignore Vue 1.x pre-hook events (Fixes #229)

---

src/backend/highlighter.js

I'm often having components rendered inside nested modals which have big `z-index`-es. It is very inconvenient for me to not be able to quickly hover over an component inside vue-devtools and not get a nice-looking hightlight (it is just hidden behind my modals). This pull request fixes that, probably in a dumb way.

make z-index bigger

---

src/backend/index.js

At the moment, the Vue DevTools will not recognize any Vue root elements if they are in a Shadow DOM.
This is what my DOM tree looks like:
The DevTools don't show anything
This is because the [`walk` function](https://github.com/vuejs/vue-devtools/blob/master/src/backend/index.js#L124-L133) only traverses `.childNodes`, but not `.shadowRoot.childNodes`.
I added the necessary code to traverse the `.shadowRoot`, and it works fine for me, now.
I also changed the Loop from `Array.prototype.forEach.call` to `node.childNodes.forEach`, because [`NodeList` supports `.forEach()`](https://developer.mozilla.org/de/docs/Web/API/NodeList), and it also works fine.
I didn't find a good/reasonable way to concat the two NodeLists before iterating (`.concat()` isn't available on `NodeList`s), so I …

Fix recognition of Vue root elements if they are in the Shadow DOM

---

src/devtools/App.vue
src/devtools/common.styl
src/devtools/components/ActionHeader.vue
src/devtools/components/DataField.vue
src/devtools/components/ScrollPane.vue
src/devtools/components/SplitPane.vue
src/devtools/views/components/ComponentInstance.vue
src/devtools/views/events/EventInspector.vue
src/devtools/views/events/EventsHistory.vue
src/devtools/views/vuex/VuexHistory.vue
src/devtools/views/vuex/VuexStateInspector.vue

~~I need a little help here, but I did most of the the leg work from a styling perspective.~~
~~According to https://bugs.chromium.org/p/chromium/issues/detail?id=608869, there should now be possible to get the value of the chrome devtool theme via `chrome.devtools.panels.themeName`.~~
~~I'm not familiar enough with chrome devtool development to know how to do it correctly, so hopefully this is an easy one for someone that knows what they're doing.~~
~~Implementation of the dark theme is done by adding a `dark` class to the root `#app` element. See change to line 4 at `src/devtools/App.vue`.~~
Edit: When installed in chrome devtools, now detects the theme automatically. Note: the dark theme doesn't work when running `npm run dev`. You will have to add the `dark` class manually to test …

Applies a dark theme, based on a global class

---

src/backend/index.js

Following up on https://github.com/vuejs/vue/issues/4957 with a bit more concrete reproduction and with a fix for it.
Okay, I've got a reproduction for that thing in a separated repo: [CLICK ME](https://github.com/andreiglingeanu/vue-devtools-bug-reproduction).
It has two problems:
1. repeated `_uid`, which is easily fixable by replacing `uid++` with something like `Math.floor(Math.random() * 100) + 1 + uid`, [here](https://github.com/vuejs/vue/blob/dev/src/core/instance/init.js#L16). See the gif in the reproduction repo
2. `vue-devtools` are accepting Vue instances which had their `Vue.config.devtools` set to false.
This pull request goes about fixing only the second concern, because the first one has to be fixed from the `vuejs/vue` repo.

respect Vue.config.devtools

---

src/devtools/views/components/ComponentInstance.vue
src/devtools/views/components/module.js

Once application grows, it becomes irritating to have to click component by component to expand the tree. Following Chrome's convention (as pointed by @kaleb) I added support for toggling the tree recursively if 'alt' key is pressed during toggle. 
I also think it's high time for 'Settings' tab to be able to customize Devtool's behaviour. E.g. for example I'd like to start with component tree fully expanded but I guess I'll just submit Feature request

Toggle component tree recursively with alt key pressed

---

src/backend/index.js

Fix #256 
I ended up doing the manual (ugly) fix because I couldn't find a basename/path package that worked on windows...

Fix components names on Windows

---

shells/dev/target/Counter.vue
shells/dev/target/store.js
src/backend/vuex.js
src/devtools/index.js
src/devtools/views/vuex/VuexStateInspector.vue
src/devtools/views/vuex/actions.js
src/devtools/views/vuex/module.js
test/specs/test.js

Hello,
This PR allows to list all getters defined in the application, just next to the state.
I have a huge application with complex getters, because my state needs to be manipulate (flatten, transformed, ...). Sometimes, it's very difficult to guess the result of the getter according to the state.
In the dev exemple I added a simple getter `isPositive` that returns `true` if `count` is upper or equal than zero.
**Implementation**:
* The action `vuex/importState` doesn't exist anymore. When the user import a state, I send an event through the bridge in order to get updated getters. The bridge will send back the `vuex:init` event to initialize the state and getters ([here](https://github.com/vuejs/vue-devtools/compare/master...AnthonySendra:master#diff-465ca035d2cf1cbe2006f96f847ee38fR33)). …

List getters in Vuex tab

---

shells/dev/target/Other.vue
src/backend/index.js

Fixes #271. `Object.keys` does not include properties from prototype chain and when `computed` is not defined on the component, all of the computed properties come from the prototype.

change enumeration method of component's computed props

---

shells/dev/target/MyClass.js
shells/dev/target/Target.vue
shells/dev/target/index.js
src/backend/index.js
test/specs/test.js

Fix #273
Also returns any instead of throwing an error if the regex doesn't match
anything.

Support Classes as types in props

---

src/devtools/views/components/ComponentInstance.vue

When a component instances are iterated via `v-for` and has more than 10 instances, the sorted order of the instances in the ComponentTree becomes broken. 
```html
<!doctype html>
<html>
<head>
<script src="https://unpkg.com/vue"></script>
</head>
<body>
<div id="app">
<table>
<tbody>
<tr v-for="row in rows">
<td v-for="val in row" is="td_component" :val="val">
</td>
</tr>
</tbody>
</table>
</div>
<script id="td_component" type="x-template">
<td>
{{ val }}
</td>
</script>
<script type="text/javascript">
td_component = {
props: ['val'],
template: '#td_component'
}
new Vue({
el: '#app',
data: {
rows: [
Array.apply(null, {length: 11}).map(Number.call, Number), // => [0,1,2,3,4,5,6,7,8,9,10]
]
},
components: {
td_component: Vue.extend(td_component),
}
})
</script>
</body>
</html>
``` …

Fix ComponentInstance.vue to be sorted properly

---

src/devtools/components/SplitPane.vue

Prevents text selection.
Before:
After:

Event modifier added

---

src/backend/index.js

Closes #289.
Allows for multiple roots using different `Vue` instances (e.g. 1 from webpack bundle, other loaded from CDN) without 'selecting' 2 instances when clicking on an instance in component tree.

fix instance id clashes with multiple roots on a page

---

src/devtools/App.vue
src/devtools/global.styl

Maybe it is not the best way to implement, but it would be nice to have a behavior that indicase the refresh.

Rotate refresh icon

---

shells/dev/target/Other.vue
shells/dev/target/Target.vue
shells/dev/target/index.js
src/devtools/components/DataField.vue
src/util.js
test/specs/test.js

Closes #276
Add support for native types like Regexp. To add a new native type (eg: Symbol), we have to update the replacer function in util
It looks like:
Which is the same colour of the devtools

Support regex

---

src/devtools/components/DataField.vue

This is for issue #123. This change disables auto-expansion of root-level objects if they have more than 4 subfields.
Alternatively, this could be implemented as a per-user option (or an option in the current page's Vue config), but since there aren't currently any other devtool config settings I thought it might be best to just implement it directly like this.
Let me know if there are any issues, thanks!

Disable expanding large objects/arrays by default

---

src/devtools/views/events/EventsHistory.vue
src/devtools/views/vuex/VuexHistory.vue

This makes the purple color used in the left side of these panes match the brighter purple color used in the right side.
Vuex before:
Vuex after:
Events before:
Events after:

Improve dark mode colors for inactive items in the Events and Vuex panes

---

shells/chrome/manifest.json

This is part of the work required to make #57 happen (as a pure WebExtension in Firefox)
The `file://*` match pattern is supposed to have 3 slashes so its actually `file:///*`.  
Chrome ignores the issue but their docs do ask for it:  https://developer.chrome.com/extensions/match_patterns
MDN has a specific warning about this: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns#Invalid_match_patterns
Tested `file:///.../todomvc/examples/vue/index.html` in Chrome and Firefox.

Add the extra slash to the file:///* match pattern

---

shells/chrome/devtools-background.html
shells/chrome/manifest.json
shells/chrome/popups/disabled.html
shells/chrome/popups/enabled.html
shells/chrome/popups/not-found.html
shells/chrome/webpack.config.js
shells/dev/webpack.config.js

This is the last set of pieces to get #57 closed and is part of the followup work to #340 
This PR needs to wait on Firefox to land the work [bug 1300590](https://bugzilla.mozilla.org/show_bug.cgi?id=1300590) such that `$0` and `inspect` bindings will work in the `devtools.inspectedWindow.eval` API.  However the patch in bugzilla is in the final throws so I wanted to get these changes up and available.

Firefox WebExtension support

---

src/devtools/components/ScrollPane.vue

**Resolves #355**
ScrollPane.vue was using "overflow overlay" which is not supported in
Firefox. Changing this to "overflow auto" fixes scrolling
in Firefox while not impacting UI or functionality in Chrome.

Fixed StateInspector scrollbars on Firefox (Except on MacOS)

---

shells/chrome/webpack.config.js

Just came across this and thought I could help out.

Fix lint errors in the shells/chrome/webpack config

---

src/devtools/components/DataField.vue
src/devtools/views/components/ComponentInspector.vue
src/util.js

I found a PR about this bug, but it didn't update the code for childs items. (https://github.com/vuejs/vue-devtools/pull/148)
Unfortunetly, I couldn't reproduce using the sandbox app installed in it, but I tested it with an application here and it fixed it. child object weren't ordered.
Thanks!

Reuse the sort by key function for sub elements in DataField component

---

src/devtools/components/ActionHeader.vue

should be able to focus search input by clicking blank area of ActionHeader

make search input as large as possible

---

src/backend/index.js

Closes #398
Thanks to @P9Q
I changed the message to be a bit more concise as well. I thought it was a bit too long with two boxes and that _Ready_ was redundant.

feat(log): add styling to console message

---

src/devtools/views/components/ComponentInstance.vue

Just a simple feature, that makes navigating component tree a little more pleasant. I often found myself frustrated that I had to point to caret to open up the tree. Now you can just double click while hovering over component in the tree to open it.

toggle component tree with doubleclick

---

src/devtools/App.vue
src/devtools/components/SplitPane.vue
src/devtools/store/index.js
src/devtools/views/components/ComponentInstance.vue

Adding the ability to split the panes horizontally or vertically based on the users preference.

Change layout depending on available space

---

src/backend/hook.js

Once an event, the event will not be removed. Because this event name become `$$event` in the off function.

fix event hook

---

shells/dev/target/Target.vue
src/devtools/components/DataField.vue
src/util.js
test/specs/test.js

This PR add support to -Infinity which is displayed currently as null.

Adding support to -Infinity

---

shells/dev/target/Date.vue
shells/dev/target/NativeTypes.vue
shells/dev/target/index.js
shells/dev/target/store.js
src/backend/index.js
src/devtools/components/DataField.vue
src/devtools/variables.styl
src/devtools/views/components/ComponentInstance.vue
src/util.js
test/specs/test.js

Fix #475 Fix #460
This PR improves `Date` and components support:
- Dates are now treated as native (like RegExp) and are fomated as such.
- Dates and reg exps are now correctly revived when time traveling in vuex.
- Import/Export of dates and reg exps now works too.
- New `_custom` API.
Example for components:
```js
{
_custom: {
type: 'component',
id: instance.__VUE_DEVTOOLS_UID__,
display: getInstanceName(instance),
value: { /* component state */ },
fields: {
abstract: true
}
}
}
```
Other example: https://gist.github.com/Akryum/f2e08df47088d5be0f933b67e90261dc
- Components are now handled in a specific way using above new feature:

Support native Date type, Components, improved RegExp, new CustomValue API

---

src/devtools/components/DataField.vue
src/devtools/components/StateInspector.vue
src/devtools/global.styl
src/devtools/variables.styl
src/devtools/views/components/ComponentInstance.vue
src/devtools/views/events/EventsHistory.vue
src/devtools/views/vuex/VuexHistory.vue

- Sections in state inspector are now collapsable
- Shift + Click and Ctrl + Click to expand/collapse all sections
- They are also redesigned
- Some style refactoring
- Vuex history items have now the same height as Events history items

Collapsable and redesigned state inspector

---

package-lock.json
package.json
shells/dev/target/Other.vue
shells/dev/target/Page1.vue
shells/dev/target/Page2.vue
shells/dev/target/Router.vue
shells/dev/target/index.js
shells/dev/target/router.js
src/backend/index.js
src/devtools/global.styl
src/devtools/views/components/ComponentInspector.vue
src/devtools/views/components/ComponentInstance.vue
test/specs/test.js

Fix #235 
- Scroll to component button in Component tree
- Center the instance to the middle of the screen
- Added some routing to target page

Scroll to component button

---

shells/chrome/manifest.json
shells/chrome/src/background.js
shells/chrome/src/detector.js
shells/chrome/src/devtools-background.js
shells/dev/index.html
shells/dev/target/Target.vue
shells/dev/target/index.js
src/backend/hook.js
src/backend/index.js
src/backend/toast.js
src/devtools/global.styl
src/devtools/index.js
src/devtools/views/components/ComponentInstance.vue
src/devtools/views/components/module.js
src/util.js

Fix #242 
- Right-click inspect
- `this.$inspect()`

Right click Inspect component + this.$inspect()

---

shells/dev/target/Target.vue
src/backend/index.js
src/devtools/App.vue
src/devtools/components/DataField.vue
src/devtools/components/StateInspector.vue
src/devtools/mixins/key-nav.js
src/devtools/variables.styl
src/util.js

Fix #74
More types (RegExp + Dates) can be enabled after #474 is merged

Editable fields

---

docs/open-in-editor.md

Hi!
In `docs/open-in-editor.md`, `openInEditor` function receives the argument as object `{ editor: 'code' }`.
It looks like a typo, because `launch-editor` should get string as name of the editor.
Also, it causes an error:
```
TypeError: s.match is not a function
at parse (/Users/c01nd01r/Projects/vue-test-prj/node_modules/shell-quote/index.js:57:26)
at Object.exports.parse (/Users/c01nd01r/Projects/vue-test-prj/node_modules/shell-quote/index.js:37:18)
at guessEditor (/Users/c01nd01r/Projects/vue-test-prj/node_modules/launch-editor/guess.js:14:23)
...
```

[docs] Typo in 'openInEditor' argument

---

shells/dev/target/Other.vue
shells/dev/target/Target.vue
src/backend/component-selector.js
src/backend/highlighter.js
src/backend/hook.js
src/backend/index.js
src/backend/utils.js
src/devtools/App.vue
src/devtools/components/ActionHeader.vue
src/devtools/index.js
src/devtools/mixins/keyboard.js
src/devtools/transitions.styl
src/devtools/variables.styl
src/devtools/views/components/ComponentTree.vue
src/devtools/views/vuex/VuexHistory.vue
test/specs/test.js

Inspired by the react developer tools and of course Chromes developer tools.
This PR adds functionality for selecting a component from the dom tree. 
Instead of just highlighting elements it highlights components themselves if the hovered element is not a Vue component it'll select the parent component.
The component tree will expand if the selected component is minimized.
Edit:
Just saw Zzuligy's [PR](https://github.com/vuejs/vue-devtools/pull/469). 
While I think that its cool that he's using the developer tools selector I still feel that our PR's have some major differences. Eg. that my version will allow the feature to also function in Safari and Firefox. 
I've messages Zzuligy to hear how he feels.

Select component from dom tree

---

src/devtools/global.styl
src/devtools/views/components/ComponentInspector.vue

All the latest improvements have been really amazing, congratulations to all who contributed.
I would just like to suggest these minor changes:
- Align the buttons to the right in the header.
_This keeps a pattern in the headers_
- Migrate the resource **Open in editor** to a button.
_In my opinion it makes more evident the existence of the resource and standardizes the feature as buttons in the header._
- Change the icon of the **Inspect DOM** resource.
_The launch icon makes it clear that the user is moved to an inspection screen._
<p align="center">
</p>
What are your thoughts on this?

Minor adjustments

---

src/devtools/views/components/ComponentInspector.vue

501 - Encode file path as URI + fix console display on Windows

---

src/backend/config.js
src/backend/highlighter.js
src/backend/index.js
src/devtools/index.js
src/devtools/views/components/module.js

Apply 'Format component names' user settings to component highlighter

Sync 'classifyComponents' settings with backend

---

shells/dev/target/NativeTypes.vue
shells/dev/target/store.js
src/backend/index.js
src/backend/router.js
src/backend/vuex.js
src/devtools/components/DataField.vue
src/devtools/components/StateInspector.vue
src/devtools/env.js
src/devtools/global.styl
src/devtools/index.js
src/devtools/variables.styl
src/devtools/views/components/ComponentInspector.vue
src/devtools/views/components/ComponentTree.vue
src/devtools/views/events/EventInspector.vue
src/devtools/views/vuex/VuexStateInspector.vue
src/util.js

- CustomValue API changes
- new `tooltip` option
- fields order retained from `value`
- Special format (using CustomValue API) for:
- Vuex Store
- VueRouter
- Component definition
- Function (Fix #133)
- Set & Map (Fix #349, Original PR #490)
- Serialization is more fault tolerant (Fix #499 Fix #507)
- Cache Custom values to prevent stack overflow (circular references, Fix #528)
- Switch the order of 'data' and 'props' sections in component inspector to better follow [the style guide](https://vuejs.org/v2/style-guide/#Component-instance-options-order-recommended)
- Performance improvements (related to #515)

Serialization & Types improvements

---

src/backend/index.js

The `== $vm0` info wasn't pushed when selecting a component

Fix == $vm0

---

src/backend/index.js
src/devtools/views/components/ComponentTree.vue

Fix regression from #542 
The button was not turning back to normal state after a component was selected.

New instance-selected bridge event

---

src/devtools/components/DataField.vue
yarn.lock

- Updated v-tooltip to latest release
- Props popover:
- Slight show delay to prevent flickering popovers with fast mouse movement
- Exclusive open-group (only on prop popover open at a time)

Props popover improvements + v-tooltip update

---

src/backend/hook.js
src/backend/index.js

514 - Move context-menu init code

---

shells/dev/target/NativeTypes.vue
src/devtools/components/DataField.vue
src/util.js

Fields of type 'String': formatted value is now escaped, fix #555

555 - Fix HTML value not escaped in DataField

---

shells/dev/target/NativeTypes.vue
src/util.js

Use prototype toString to prevent bad serialization

---

src/devtools/components/DataField.vue

In dark mode, changed strings `"` from black to red.

Fix double quotes color in Dark mode

---

shells/electron/package.json
shells/electron/yarn.lock

This PR downgrades electron version to latest stable release, as the previous one `1.8.1` is still marked as `beta`, and it doesn't open electron properly with socket.io in background on Node >= 8.
I also updated package version to 1.0.0, as recommended here: https://docs.npmjs.com/getting-started/semantic-versioning#semver-for-publishers

Fix electron shell

---

README.md
shells/electron/package.json

Because of caret in version `^1.7.11` - downloaded electron was still `1.8.1`. Given official information on electron readme `Electron does not follow semantic versioning` I locked it to be exactly `1.7.11`.
I also update link copy in readme to be more explicit.

Update electron shell

---

src/devtools/env.js

Redefining ownProperties on Vue.prototype causes error on page refresh, as it executes `initEnv` once again. I check for presence of one of the properties assigned there so it doesn't reinitiate it when already initialized.

Fix initEnv, so it doesn't crash on page refresh

---

shells/electron/README.md

Documentation about using the electron dev tool remotely is missing a couple of underscores after `__VUE_DEVTOOLS__HOST`

Add missing underscore to electron doc

---

shells/electron/README.md
shells/electron/index.js
shells/electron/src/backend.js
shells/electron/src/devtools.js

This PR addresses #597 as well as some other thing by the way, like:
- port overriding - it turned out it was not entirely possible. I also updated documentation with necessary informations of how to do it.
- it makes it possible to reset default port, which might be useful while debugging using ngrok proxy, where simple link proxies to proper port on localhost and thus connection URL doesn't need additional port.
By introducing above changes it also became possible to inspect staging applications if necessary, by proxying devtools middleware through ngrok. Just as with HTTPS on localhost :)

(fixes #597) Allow debugging through proxy

---

shells/dev/target/NativeTypes.vue
shells/dev/target/store.js
src/util.js

This change has some slight improvements for displaying values. The first part makes it so Symbols are shown as 'Symbol(Description)' instead of 'Symbol'. The second part handles functions which have their parameters spread over multiple lines. In 4.1.0 this type of function causes an exception (#568) and in the latest code it shows the parameter list as '(?)'. With this change, all white space between parameters will be normalized.

improve the display of symbols and functions

---

src/devtools/locales/en.js
src/devtools/views/components/ComponentInstance.vue

I added a title attribute: "Available as $vm0 in the console."
Also changed `== $vm0` to `= $vm0` since it seems like something was assigned instead of just equal to something. I was also considering maybe `= window.$vm0` to make it even more clear?
Let me know what you think.

Make ability to send vm to console slightly more obvious

---

shells/dev/target/NativeTypes.vue
src/util.js

Related to #568
Sometimes a Function Proxy gets inspected by `getCustomFunctionDetails()`, which breaks because `Function.prototype.toString` doesn't always work with Proxy objects.
This patch simply catches the `TypeError` and allows `vue-devtools` to continue rendering the Component details even if it contains funky Function Proxies.  Currently if this occurs the Component detail view doesn't show, which leaves developers stuck tracking down the cause of the issue without the help of `vue-devtools`.  This patch will at least allow the Component details to render, but the Function Proxy in question will not show argument details.
There might be a way to continue rendering the arguments for certain Function Proxies but I don't think it would be completely general.

Catch exception for Function.toString on Proxies etc.

---

src/backend/index.js

We got a same issue to #269 . I don't know the real reason, but I believe this patch will fix it.
BTW, When I inspect the code, I found something, may be useful for finding the real reason @yyx990803 :
In the backend.js, when the detected `rootInstance`  is a `VueComponent`, we'll loose the `<Root>`

Fix loosing <Root> #269

---

src/util.js

Fix #708 
- When `func` argument is a Proxy function than `toString` can return function.
- Add additional check to `matches`
- Add check that `func.name` is a string. With proxy example in the issue description `func.name` will throw an error

Fix custom function details parsing

---

src/devtools/App.vue

Fixes #667 
It's easy as that 😄 
I can image this is not desirable code, though, since it mixes functional code with a platform-specific quirk.
Any ideas?

Prevent chrome devtools from opening the print modal

---

src/devtools/views/components/ComponentInspector.vue

Precompiled 3rd party components still need to define a `name` on components, because the `__file` property is not currently added in production. For privacy and practical reasons, we never want to add the full path to `__file` in production, but we want to start adding setting the file's basename in `vue-loader` and `rollup-plugin-vue`.
For this to work though, we'll want to start checking whether `__file` is a path here and only allow it to be opened if it is.

Only open file if it's a full path

---

cypress/integration/events-tab.js
cypress/integration/vuex-tab.js
package.json
shells/dev/target/Counter.vue
shells/dev/target/EventChild.vue
shells/dev/target/Events.vue
src/backend/vuex.js
src/bridge.js
src/devtools/components/ScrollPane.vue
src/devtools/components/StateInspector.vue
src/devtools/index.js
src/devtools/mixins/entry-list.js
src/devtools/plugins.js
src/devtools/views/events/EventsHistory.vue
src/devtools/views/vuex/VuexHistory.vue
src/devtools/views/vuex/VuexStateInspector.vue
src/devtools/views/vuex/actions.js
src/devtools/views/vuex/cache.js
src/devtools/views/vuex/module.js
src/devtools/views/vuex/resolve.js
src/shared-data.js
src/util.js
yarn.lock

Refactor vuex snapshots

---

cypress/integration/vuex-edit.js
cypress/integration/vuex-tab.js
shells/dev/target/NativeTypes.vue
src/backend/vuex.js
src/devtools/components/DataField.vue
src/devtools/components/StateInspector.vue
src/devtools/index.js
src/devtools/mixins/data-field-edit.js
src/devtools/views/vuex/VuexStateInspector.vue
src/devtools/views/vuex/actions.js
src/devtools/views/vuex/module.js

Make Vuex state fields editable. Closes https://github.com/vuejs/vue-devtools/issues/699

Editable vuex state

---

src/devtools/views/vuex/VuexStateInspector.vue

Prevents opening the console when you press ESC when importing the state.

Add modifier

---

src/devtools/components/GroupDropdown.vue

Routing Tab Header doesnt adjust height on smaller screens

fix routing tab header position

---

src/devtools/App.vue
src/devtools/components/SplitPane.vue

There are no possibility to scroll panes when using devtools as extension of nw.js environment. These changes fix this problem.

fix: nw.js splitPanes scrolling

---

shells/electron/package.json

While installing native-script-vue, I was alerted to a critical security vulnerability and wanted to correct the issue. (https://nodesecurity.io/advisories/732)
Security is important. :-)
I bumped the minor version of electron to one that patches the vulnerability.
App developers don't need to do anything.
By only bumping the minor version I hope there are none.
Merge?
Addresses issue #804
Thanks to @tupperkion for their fantastic PR format.

Bump to patched electron version

---

cypress/integration/components-tab.js
shells/dev/target/Target.vue
src/devtools/views/components/ComponentInstance.vue

#827: Show 0 as a valid key in the component tree

---

cypress/integration/vuex-tab.js
shells/dev/target/store.js
src/backend/vuex.js

closes #773 , closes #792, closes #802 
All handlers are `wrappedMutationHandler ` with only 1 argument - `payload`

#773: Fix payload on replaying mutation

---

src/backend/index.js
src/devtools/views/settings/GlobalPreferences.vue
src/shared-data.js
src/util.js

Closes #669
@Akryum I tried to achieve this feature without introducing a bunch of new code and reused the existing editing feature. Prop manipulation is OFF by default and must be enabled in the settings.
Also, the props edit feature is only implemented for Vue 2. If you think it should be added for v1 let me know.
If you're willing to merge this feature, ping me and I'll add some tests

feat: Make props editable, closes #669

---

src/devtools/style/global.styl

Adjust color of menu arrows when UI is in dark mode

Make Dark Mode Arrows More Visible

---

src/devtools/style/global.styl

In dark mode, mouse icons were the same color as background of tooltip:

Adjusts styling of tooltip icons in dark-mode

---

src/backend/highlighter.js
src/backend/toast.js

Content Security Policy prevents the usage of inline styles on DOM elements, unless the insecure 'unsafe-inline' rule is used. This can be worked around by setting styles through the JS DOM API.
Fixes #905

fix: CSP inline style violations (fix #905)

---

src/backend/vuex.js

In the latest Firefox and Google browsers, state data tree will not load for error:[mutation.handlers is undefined], because mutation handler actually passes is null (store. _mutations is empty) while pushing the handlers value as an element to the base mutations array, just add robust check.

Fix browser env mutation.handlers is undefined

---

types/index.d.ts

I have added type def for connect.
Issue: https://github.com/vuejs/vue-devtools/issues/779

[Typescript] added type definitions

---

src/devtools/views/events/module.js
src/devtools/views/vuex/module.js

In mutation or event filtering, it is currently possible to filter using regexp, but not to use the `/` char in a regex.
This prevents to filter on namespaced mutation name, which is sad. My personnal example is that I wanted to filter out the mutation (core/logger/log) with the following regexp : `/^((?!core\/logger\/log).)*$/` and it didn't work. Filtering with `/^((?!logger).)*$/` did work as expected, but filters too much.
I checked the code in `src/devtools/views/vuex/module.js` an  `src/devtools/views/action/module.js`
The regexp `REGEX_RE = /^\/(.*?)\/(\w*)/` cuts the regexp at the first `/` encountered, making it impossible to use this char in a regexp, no matter how we try to escape it.
I see several ways to do solve it: 
- I'm not sure why the `.*` in REGEXP_RE is not greedy. …

Change REGEX_RE to allow use of / in filters

---

src/backend/index.js
src/devtools/views/settings/GlobalPreferences.vue
src/shared-data.js

Closes #685 
@Akryum Any suggestions or changes I should make before we can merge this?

feat: Add a setting for "vue-devtools Detected Vue" console log, closes #685

---

src/util.js

Error was throwed on editing data in devtools only when component had not props
(#882)

fix: error on edit data of component without properties in devtools (#882)

---

src/backend/hook.js

When the vuex store does not have `registerModule`, `flushStoreModules` will return `undefined` and make the following calls on hook.storeModules failed.
This happened in my early version of vuex apps.

fix(vuex): make sure flushStoreModules return array

---

src/backend/index.js
src/backend/vuex.js
src/devtools/views/settings/GlobalPreferences.vue
src/shared-data.js

Solves #939 
Contains 2 bugfixes.
So as I mentioned in the source issue, the config reading isn't worked for some reason, but instead of applying a separate option, my thought was to better to figure out the current VueX version. 
Since the `commit` not exist in the older (as you call `legacy`) versions my ide was that to check this function and the existence of it. 
There was an other compatibility issue as well which caused by how the payload was passed to the mutation handler on legacy mode. I've solved this with simply convert the payload to an array when it's a legacy mode.

#939 Refactor legacy VueX checking

---

src/devtools/views/settings/SettingsTab.vue

I created issue #972 before.
Settings tab is not able to scroll down.
Because even there is a CSS to make this tab as scrollable, 
cascading rule makes `overflow: auto` ignored.
So I checked if there is a same class name with `settings` and put `!important` to make high priority.

fix: style issue on Settings Tab

---

packages/app-backend/src/vuex.js

Since the old VueX store doesn't have namespaces the devtools failed to load because of that. So i've added a fallback for it

fix: fallback for store modules namespace map

---

packages/shell-chrome/popups/disabled.html
packages/shell-chrome/popups/disabled.nuxt.html
packages/shell-chrome/popups/enabled.html
packages/shell-chrome/popups/enabled.nuxt.html
packages/shell-chrome/popups/not-found.html
packages/shell-chrome/popups/popup.css

Fixes: #1014
This PR styles all popups to be more consistent with the rest of the devtools.
Using the same fonts and colors if available. Also tweaks the spacing so the text doesn't appear to be off center anymore.

style popups

---

packages/shell-chrome/src/devtools-background.js

clearTimeout when already created or retry limit reached

perf(devtools-background) clearTimeout when needed

---

README.md

taking care of issue #531 by adding a line in the Usage Notes

mentioning that the events tab is only for custom events

---

packages/app-backend-vue3/src/components/util.ts

Vue3: Fixes issue with `__VUE_DEVTOOLS_APP_RECORD` being accessed through `.__app` instead of `.app` as reported in https://github.com/vuejs/vue-devtools/issues/1246.

Vue3: Fixes issue with __VUE_DEVTOOLS_APP_RECORD being undefined

---

README.md

* semantic proposal on line 27
* plus minor formatting proposals

Fixed typo on line 38

---

packages/shell-chrome/src/devtools-background.js

Recent fix fa17699aba2bd9c76dd86d63143b9a28d1d3b05f has a missing argument for `Object.Keys()`.

missing argument for `Object.keys`

---

docs/plugin/api-reference.md
packages/api/src/api/api.ts
packages/api/src/api/hooks.ts
packages/app-backend-api/src/api.ts
packages/app-backend-api/src/hooks.ts
packages/app-backend-core/src/index.ts
packages/app-backend-vue3/src/components/util.ts
packages/app-backend-vue3/src/index.ts
packages/shared-utils/src/consts.ts
packages/shell-dev-vue3/src/devtools-plugin/index.js

I’ve added utility API
- getComponentInstances
- highlightElement
- unhighlightElement
These APIs allow 3rd parties to highlight the elements of a component in the custom inspector.
In the Vue i18n use case, it's the i18n resources inspector.
The i18n resources inspector enumerates the scopes associated with a vue i18n component.
When the user selects a scope, it would be nice to be able to highlight the component to get a good DX.
https://user-images.githubusercontent.com/72989/110752332-7bda4f80-8288-11eb-816d-41b267199e65.mov

feat: add utilities API

---

packages/app-backend-core/src/timeline.ts

`appRecord` is `undefined` in some weird cases, like the one in the reproduction link in the issue: intlify/vue-i18n-next#293. I guess it's because the devtools is not aware of the app yet? I'm not sure.
This fixes intlify/vue-i18n-next#293. I reported it there because I didn't know how to reproduce it without vue-i18n, and at the time I wasn't sure if it was a vue-devtools bug or vue-i18n bug.

fix(timeline): error when no appRecord found

---

packages/app-backend-vue2/src/plugin.ts

I found Vue Devtools 6 fails to handle Vuex modules without namespace (`namespaced = false`).
The `getters` of that kind of modules seems to be got from `module.context.getters`.
---
add details...
I fixed the part of `formatStoreForInspectorState` and it is called from following part.
https://github.com/vuejs/vue-devtools/blob/d5e0579b35a7c93869ddb839e3863219202ab0ec/packages/app-backend-vue2/src/plugin.ts#L101-L114
This means `getters` argument of `formatStoreForInspectorState` is `store._makeLocalGettersCache`, but `store._makeLocalGettersCache` doesn't look includes `root` modules' ones and **un** -namespaced moduels' ones but only includes namespaced modules' ones. 
So before my fixing, `TypeError: Cannot convert undefined or null to object` error occurs at line 350 since getters of …

fix(vue2): handling un-namespaced vuex module

---

docs/plugin/plugins-guide.md

Minor fix- adds a missing declaration. Matches the declarations of `node` that are used elsewhere in the docs.

docs: Add missing variable declaration

---

docs/.vitepress/config.js

- 'next' points to non-existent location, 404 error on Github.
- 'main' should be what you're looking for here.

docs: fix edit links

---

packages/api/src/env.ts

`navigator` maybe created by miniapp(or other sth), but `window` still is undefined

fix: window is undefined cause an error

---

packages/app-backend-vue2/src/components/tree.ts

Hi, @Akryum.
I've found that the `async capture` method (packages/app-backend-vue2/src/components/tree.ts)  introduced  last week lead to some cases on Vue 2. 
The Vue2 version of devtools was unable to open the **App** node, report the component structure is illegal:
When headed towards the devtool's console, it triggers a warning of TypeError of promise not been correctly unwrapped.
I found that the error is probably caused by the asynchronous calls inside the   `capture` method not been properly handled in order. Hence I've  composed the function calls with `await` keyword, which solved the problem

fix(vue2): fix async capture errors

---

packages/app-backend-vue3/src/components/data.ts

Based on #1542 , I modified that to support both `effect.raw` and `effect.fn`.

fix(dataField): support effect below vue 3.2

---

packages/app-backend-vue3/src/index.ts

With reference to #1507 , I found that `Transition` was defined as a functional component in vue 3.x, which caused crash on showing render code. To fix it conditional statement is added.

fix(vue3): render code crash on transition component

---

packages/app-backend-vue2/src/components/tree.ts

Fix the issue #1433 
Reproduction repo - https://github.com/ItMaga/vue-devtools-bug
This is incorrect behavior `vuedraggable` library, but i think devtools should continue to work correctly

fix: empty `$vnode.data`

---

packages/app-frontend/src/features/components/ComponentsInspector.vue
packages/app-frontend/src/features/components/SelectedComponentPane.vue
packages/app-frontend/src/locales/en.js

According to #1532 and #1281 , I try to make some modifications. Shortcut of filter components was changed from `Ctrl + F` to `Alt + F`. After select a component, we can press `Alt + D` to filter state. The same time related tooltip was added.

feat: modify shortcut and add tooltips

---

packages/shell-electron/package.json
packages/shell-electron/types/index.d.ts

Hello,
I noticed that the `init` method exported out of `packages\shell-electron\index.js` was missing from the type file. This pull request fixes that. 
Additionally the type information for the `connect` method was missing the `{ io, showToast, app}` object as an optional prop. This pull request adds it as a parameter named "options", where the option properties are defined in the `ConnectOptions` interface.
You'll also notice that this pull request adds `vue` as a dev dependency so that the `Vue` type can included in the type definitions
Before this change Typescript show type errors
Typescript errors are gone

fix(types): Add Missing Methods & Props to "./packages/shell-electron/types"

---

packages/app-backend-vue3/src/components/tree.ts

Based on #1592 and #1529 , I added `default` and `fallback` tag to suspense components. It will be displayed like this:

feat: optimize suspense tag

---

packages/api/src/proxy.ts

fix(plugin): early proxy `hook` can be `undefined`

---

packages/app-backend-vue3/src/components/data.ts
packages/shell-dev-vue3/src/Provide.vue

Fixes and closes #1643 .
I also make it support default value, for example change the test component `Provide` of devtools to:
```js
inject: {
i: {from: 'injectedta', default: 'wrong key name'}, 
[Symbol('alias')]: symbolForProvided
},
```
Then on the devtools panel showed:

fix: display injection of 'symbol' key

---

packages/shell-chrome/src/devtools-background.js

Solves the following error when opening browser devtools on a non-vue page
```
TypeError: can't access property "Vue", window.__VUE_DEVTOOLS_GLOBAL_HOOK__ is undefined
```

fix: avoid exception when opening devtools on a non-vue page

---

docs/guide/custom-vue2-app-scan-selector.md
packages/app-backend-core/src/app.ts
packages/app-backend-core/src/index.ts
packages/app-backend-core/src/legacy/scan.ts
packages/app-backend-core/src/page-config.ts

fix: support vue2 app debugging in micro-app

---

packages/shared-utils/src/util.ts

This bug may causes the UI 'Component Filter' to not work properly

fix: utils.classify may causes '"replace" is not a function' exception

---

packages/app-backend-vue2/package.json
packages/app-backend-vue2/src/components/data.ts
yarn.lock

Fixes https://github.com/vuejs/devtools/issues/949 by adding the specific polyfill from core-js. It'd be nice if @dacotagh validates it.

fix: Add object entries polyfill for app-backend-vue2

---

packages/app-backend-core/src/app.ts

fix(vue2): Use the super constructor when the instance is a VueComponent

---

packages/app-backend-core/src/app.ts

This fixes a bug where more than two components with the same name could not be held apart by the backend. It is looking for `defaultId:count`while counting references but then names the reference `defaultId_count` this resulted in a maximum of two components with the same name being recognized (that is clickable) in the devtools.

fix: generated app id not deduped

---

packages/app-frontend/src/features/welcome/WelcomeSlideshow.vue

Thank you for all your hard work on the awesome devtools!
This is a minor edit to fix a typo in the title of the welcome slide show. This is missing an "a" before "little tour". Also, I would say it's more common (in American English, at least) to say "take a tour" vs. "have a tour", though they may both be correct.
n/a
---
- [ x Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

fix: typo in title of welcome slideshow

---

packages/shell-electron/server.js

close #1813
Added the cors origin config to socket.io server.
https://socket.io/docs/v4/migrating-from-2-x-to-3-0/#cors-handling
https://github.com/expressjs/cors#configuration-options
---

fix(electron): enable CORS for socket.io server (fix #1813)

---

packages/app-frontend/src/features/header/AppHeader.vue

in a small screen width, the buttons to select an element, refresh and settings, do not fit due to the fact that the inspector and timeline buttons have a label
before: 
after:
I think that it can be done better, but I just corrected what bothered me
---
- [X ] Read the [Contributing Guidelines](https://devtools.vuejs.org/guide/contributing.html).
- [ X] Read the [Pull Request Guidelines](https://devtools.vuejs.org/guide/contributing.html#pull-request-guidelines) and follow the [Commit Convention](https://github.com/vuejs/devtools/blob/main/.github/commit-convention.md).
- [X ] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that …

fix: AppMainMenu: use compact layout if screen is narrow

---

packages/app-backend-vue3/src/components/util.ts

When we import and use  a 3rd Party component in `<script setup>` like in the following example, it will show up as `<Anonymous Component>` in devtools.
```html
<script setup>
import Child from 'cool-ui-library'
</script>
<template>
<Child />
</template
```
This PR makes devtools fall back on the internal `__name` property added by `@vitejs/plugin-vue` (this name is derrived from the filename) if no explicit name has been set.
I'm not sure how to add a test case for this. But I hope the fix is trivial enough to do without one.
---
- [ x Read the [Pull Request Guidelines](https://devtools.vuejs.org/guide/contributing.html#pull-request-guidelines) and follow the [Commit Convention](https://github.com/vuejs/devtools/blob/main/.github/commit-convention.md).

fix(vue3): ensure 3rd party components directly imported in script setup do not show up as `Anonymous Component` in devtools

---

packages/app-backend-vue3/src/components/data.ts

Previously check was only a `startsWith()` leading to not displaying names like `userXXX`. With this regex, we check if the first part of our string before another uppercase starts with `use`.
Fixing issue #1971 
---

fix: Better check if data name starts with use (fix: #1971)

---

packages/docs/src/.vitepress/config.js
packages/docs/src/guide/contributing.md
packages/docs/src/guide/devtools-perf.md

- Correct typing
- Update repo name
- Fix edit docs link
- [X ] Read the [Contributing Guidelines](https://devtools.vuejs.org/guide/contributing.html).
- [ X] Read the [Pull Request Guidelines](https://devtools.vuejs.org/guide/contributing.html#pull-request-guidelines) and follow the [Commit Convention](https://github.com/vuejs/devtools/blob/main/.github/commit-convention.md).
- [ X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).

docs: Correct typing & fix edit document links

---

packages/app-backend-vue3/src/components/data.ts

The Injects values are incorrectly coalescing falsy values to their default values when the component is written in Options mode.
If a parent component provides a falsy value (false, null, 0, "", etc.), then a child component written in Options mode will incorrectly coalese that and show the default value given for the inject.
---

fix(vue3): inject value showing default over falsy value

---

packages/app-backend-vue3/src/components/util.ts

fix: #2049
Optimize the priority of calculating the displayed name of the component on the devtool.
The registered name should have a higher display priority than the file name (the detail is in the issue).
---

fix(vue3): Optimize the priority of calculating the displayed name of the component on the devtool

---

packages/app-frontend/src/mixins/data-field-edit.js
packages/shared-utils/src/util.ts
packages/shell-dev-vue2/src/NativeTypes.vue
packages/shell-dev-vue3/src/NativeTypes.vue

fix: #2036
- Support browser native object BigInt
- Make BigInt editable
Before:
After:
---

feat: support native type BigInt

---

packages/app-backend-vue3/src/components/data.ts

See  #2037 for description. I have tested this on Chrome and it works as expected.

fix(vue3): prevent mixin leakage caused by inspection, fix #2037

---

packages/app-backend-core/src/index.ts
packages/app-backend-core/src/perf.ts
packages/app-backend-core/src/plugin.ts
packages/app-backend-core/src/timeline.ts

fix(index.ts): add null checks for appRecord and appRecord.instanceMap to prevent errors when accessing properties
Fixes #1892

fix: add null checks for appRecord and appRecord.instanceMap, fix #1892

---

packages/app-backend-vue3/src/components/data.ts

fix: #2046 
fix: #2063
fix: #2060
Fix the declared camelCase event that cannot be recognized.
the declaredEmits are not normalized to kebab case, which results in the mismatching with the declared events on the parent component side.
---

fix(vue3): Fix the declared camelCase event cannot be recognized

---

packages/app-frontend/src/features/timeline/TimelineEventList.vue
packages/app-frontend/src/features/timeline/composable/layers.ts

fix: #2108
Hiding a selected layer will cause many errors on hovering other layers, and will break the timeline when refreshing the page.
Reset layer status when hiding the selected layer will eliminate this error.
---

fix(timeline): Reset layer status when selected layer is hidden in timeline

---

packages/app-backend-vue2/src/plugin.ts

Fix: #1669
Refs: https://github.com/vuejs/devtools/issues/1669#issuecomment-1678899513
As commented above, "Save focused element path in localStorage" → "Revive focusing on refresh page" will easily result in throwing error, I think somehow missing a module is normal behavior, throwing the error is not necessary.
---

fix(vue2): Remove throwing error on inspect missing vuex module

---

.circleci/config.yml

It seems like due to the limitation of memory of the container, CI always fails. After trying to change the container to a bigger one (medium+), it succeeds.
Reproduction on my job: https://app.circleci.com/pipelines/github/Azurewarth0920/devtools/1/workflows/a5f8b619-6d0f-42ad-9586-61d282f7c65b/jobs/1
---

ci: Fix broken CircleCI build job

---

packages/app-frontend/src/features/inspector/DataField.vue
packages/app-frontend/src/mixins/data-field-edit.js
packages/shared-utils/src/util.ts
packages/shell-dev-vue3/src/NativeTypes.vue

Fix: #869
enable edit mode on native date object by using `<input type="datetime-local">`
Screenshot:
https://github.com/vuejs/devtools/assets/22590005/58c8e9d1-a665-4db3-9fc4-45bfd9fb4268
---

feat(component): Add edit mode on native date object

---

packages/app-frontend/src/components/ActionHeader.vue

When the width of the vue-devtools is not large, the action icons disappear
Example of an error is shown in the screenshot.

Fix: action icon size

---

packages/app-backend-vue3/src/components/data.ts

Problem: if you use third-party ui libraries, the instance of the used components gets into the "setup" block and is mixed with the instance of your component, which is very annoying.
Solution: Added check for component and redirect components to "script(other)" block
---

fix(component): filtering components of third-party libraries to script(other)

---

packages/app-backend-vue3/src/components/util.ts
packages/app-backend-vue3/src/util.ts
packages/shared-utils/src/util.ts
packages/shell-dev-vue3/src/App.vue
packages/shell-dev-vue3/src/IndexComponent/index.vue

This PR relates to https://github.com/vuejs/devtools/issues/387. Sometimes developers have components nested inside directories and follow classic Node approach of naming them `/index.${extenstion}`, in this case `/index.vue`. Devtools currently display every component as `<Index>` unless you specify `name`. This PR will check for those components and use parent directory as component name.
Compnent is defined in `src/IndexComponent/index.vue`
Before:
After:
I’ve also taken the chance to use `basename` function from `@vue/shared-utils` and removed same command form Vue 3 backend namespace.
---

feat(component): Add support for better naming of `/index.vue` components

---

packages/app-backend-vue3/src/components/data.ts

Fix: #2061
As the reason: https://github.com/vuejs/core/issues/4866#issuecomment-1128313856
The `setupState` is not exposed in production mode, so we cannot inspect the internal state of built library described in #2061 
Inspired by https://github.com/vuejs/core/issues/8515#issuecomment-1581906384, we can use `exposed` field to inspect the state.
---

fix(vue3): Show the imported component setup state by using exposed in production

---

packages/app-frontend/src/features/timeline/TimelineEventInspector.vue

I fixed bug #1837 which highlighted the value expressed in ms 1000 times higher than the reality.
---

fix(timeline): incorrect unit for group duration (fix issue #1837)

---

packages/app-backend-core/src/app.ts

Fix: #2078
Check the existence of the root element as the root element may be empty.
(Eg. described in #2078, using custom render that doesn't generate DOM may cause the empty root)
---

fix(iframe): Add optional chaining on unsafe-type element

---

packages/docs/src/plugin/api-reference.md

fix(docs): change variable name in getComponentName code snippet
Change the variable name `name` to `componentName` in the `getComponentName` code snippet.
In the getComponentName documentation, change the name of the variable
```
api.on.inspectComponent(async payload => {
if (payload.instanceData) {
const componentName = await api.getComponentName(payload.componentInstance)
payload.instanceData.state.push({
type: stateType,
key: 'component name',
value: name -------> changed to componentName
})
}
})
```
---

docs: change variable name in getComponentName code snippet

---

packages/app-frontend/src/features/components/ComponentsInspector.vue
packages/app-frontend/src/features/components/SelectedComponentPane.vue

PR about hotkeys from here
On Mac "option" key modifies the resulted `event.key` value (`s` becomes `ß`) that's why check `event.key === 's'` doesn't work.
According to [mdn's KeyboardEvent: code article](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) we can't fix the bug with `event.code === 'KeyS'` because on different keyboard layouts symbol will be different.
```
For example, the code returned is "KeyQ" for the Q key on a QWERTY layout keyboard,
but the same code value also represents the ' key on Dvorak keyboards and the A key
on AZERTY keyboards. 
That makes it impossible to use the value of code to determine what the name of the 
key is to users if they're not using an anticipated keyboard layout.
```
So I just added the resulting keys to the whitelist.
There …

fix: mac hotkeys (fix #1907)

---

packages/docs/src/guide/faq.md

"anyaway" -to> "anyway"
I have corrected a very small typo
I was working on my project and Vue Devtools wasn't showing up so I read the FAQ and found this typo, so thought to help :)
---

docs: Typo correction faq.md

---

packages/shared-utils/src/util.ts
packages/shell-electron/src/backend.js

Added chunking to bridge `send` function, in the electron shell backend, to prevent crash when sending very large payload.
Added chunk function, in utils, based on [Andrei R](https://stackoverflow.com/a/37826698) answer on stackoverflow.
Socket.io's [size limit is 1 mb](https://socket.io/fr/how-to/upload-a-file#maxhttpbuffersize-limit). When sending a payload larger than that, the socket connection would hang up on it's own and the devtools would be disconnected.
This PR could potentially fix many crashing issue when working with large projects. Some related issues are:
- #1386
- #1252
- #1287
However, this fix is only applied on the standalone electron app. This is why I am not referencing this PR as a direct fix for those issues.
---

fix(electron): chunk message data

---

packages/docs/src/.vitepress/config.js

(reported by @yyx990803 ) the key used in the docs atm is the crawler api key, meaning it have more rights than just searching the index (crud records, delete index etc.), so I've rotated it in order to fix the crawler, and generated a search only one for your docs
I'll wait for this PR to be merged to delete the current key, so your search still works in the meantime

docs: use Algolia search API key
